[package]

name = "examples"
version = "0.0.1"
authors = ["John P Mayer Jr <john.p.mayer.jr@gmail.com>"]

[dependencies.websocket-protocol]
git = "https://github.com/jmpspace/websocket-protocol.git"

[profile.dev]
opt-level = 0
debug = true